# 线上配置文件

spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: 'jdbc:mysql:'
    username:
    password:
  # session 失效时间
  session:
    timeout: 86400

  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
    password:

server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain: 服务器IP地址或者域名
        same-site: lax
        secure: false
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0


